WebTeste - Separado - Copia/WebTeste1/Models/Aluno.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace WebTeste
{
    public class Aluno : IEntidade
    {
        [Required(ErrorMessage = "Insira a matrícula do aluno.", AllowEmptyStrings = false)]
        [Range(1, 999999999, ErrorMessage = "Matrícula deve estar entre 1 e 999999999.")]
        public int? Matricula { get; set; }

        [Required(ErrorMessage = "Insira nome do aluno.", AllowEmptyStrings = false)]
        [StringLength(100, MinimumLength = 1)]
        public string? Nome { get; set; }

        [Required(ErrorMessage = "Selecione o sexo do aluno.", AllowEmptyStrings = false)]
        public EnumeradorSexo? Sexo { get; set; }

        [Required(ErrorMessage = "Insira a data de nascimento do aluno.", AllowEmptyStrings = false)]
        [DataType(DataType.Date, ErrorMessage = "Isto não é uma data.")]
        [Display(Name = "Data de nascimento")]
        [Range(typeof(DateTime), "01/01/1950", "01/01/2022", ErrorMessage = "O ano de nascimento do aluno deve ser pelo menos 1950 e no máximo 01/01/2022.")]
        public DateTime? Nascimento { get; set; }

        [StringLength(14, MinimumLength = 11, ErrorMessage = "CPF deve ter 11 dígitos.")]
        public string? CPF { get; set; }

        public override bool Equals(Object aluno)
        {
            return aluno is Aluno alunoComparado && Matricula.Equals(alunoComparado.Matricula);
        }
        public override int GetHashCode()
        {
            return (int)Matricula;
        }
        public override string ToString()
        {
            return $"Matrícula: {Matricula}\nNome: {Nome}\nSexo: {Sexo}\nNascimento: {Nascimento:dd/MM/yyyy}\nCPF: {CPF}";
        }
    }
}

WebTeste - Separado - Copia/WebTeste1/Controllers/AlunoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text.RegularExpressions;

namespace WebTeste.Controllers
{
    public class AlunoController : Controller
    {
        private readonly RepositorioAluno repositorioAluno = new();
        // GET: Aluno
        public ActionResult Index(string searchString, string option)
        {
            var alunosLista = from aluno in repositorioAluno.GetAll()
                              select aluno;
            if (string.IsNullOrEmpty(option) && string.IsNullOrWhiteSpace(searchString))
            {
                return View(alunosLista);
            }
            if (string.IsNullOrEmpty(option) ^ string.IsNullOrWhiteSpace(searchString))
            {
                return View(alunosLista);
            }
            else if (option.Equals("Nome"))
            {
                if (!string.IsNullOrEmpty(searchString))
                {
                    alunosLista = alunosLista.Where(a => a.Nome.Contains(searchString, StringComparison.InvariantCultureIgnoreCase));
                }
                return View(alunosLista);
            }
            else if(option.Equals("Matricula"))
            {
                if (!string.IsNullOrEmpty(searchString) && Regex.IsMatch(searchString, "^[0-9]*$"))
                {
                    alunosLista = alunosLista.Where(a => a.Matricula.Equals(Convert.ToInt32(searchString)));
                }
                else
                {
                    ViewBag.Message = "Insira apenas números para buscar por matrícula.";
                }
                return View(alunosLista);
            }
            else
            {
                return View(repositorioAluno.GetAll());
            }
        }

        // GET: Aluno/Create
        public ActionResult Create()
        {
            List<SelectListItem> sex_items = new()
            {
                new SelectListItem() { Text = "Masculino", Value = "Masculino" },
                new SelectListItem() { Text = "Feminino", Value = "Feminino" }
            };
            ViewBag.Sexo = sex_items;

            return View();
        }

        // POST: Aluno/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Aluno aluno)
        {
            List<SelectListItem> sex_items = new()
            {
                new SelectListItem() { Text = "Masculino", Value = "Masculino" },
                new SelectListItem() { Text = "Feminino", Value = "Feminino" }
            };
            ViewBag.Sexo = sex_items;

            if (!string.IsNullOrWhiteSpace(aluno.CPF))
            {
                string novoCpf = Regex.Replace(aluno.CPF, "[^0-9]", "");
                if (novoCpf.Length != 11)
                {
                    ModelState.AddModelError("CPF", "O CPF deve conter 11 dígitos.");
                    return View(aluno);
                }
                for (var i = 0; i < 11; i++)
                {
                    if (!char.IsDigit(novoCpf[i]))
                    {
                        ModelState.AddModelError("CPF", "O CPF deve conter apenas dígitos.");
                    }
                }
                var intCpf = new int[11];
                int soma = 0;
                for (int i = 0, j = 10; i < 11; i++, j--)
                {
                    var sucessoNaConversao = int.TryParse(novoCpf[i].ToString(), out var valor);
                    intCpf[i] = valor;
                    if (j >= 2 && sucessoNaConversao)
                    {
                        soma += intCpf[i] * j;
                    }
                }
                var cpfComTodosDigitosIguais = true;
                for (var i = 1; i < 11; i++)
                {
                    if (intCpf[0] != intCpf[i])
                    {
                        cpfComTodosDigitosIguais = false;
                        break;
                    }
                }
                if (cpfComTodosDigitosIguais)
                {
                    ModelState.AddModelError("CPF", "CPF's com todos dígitos iguais são inválidos.");
                }
                int penultimoDigito = (soma * 10) % 11;
                if (penultimoDigito == 10)
                {
                    penultimoDigito = 0;
                }
                if (penultimoDigito != intCpf[9])
                {
                    ModelState.AddModelError("CPF", "O CPF inserido é inválido.");
                }
                soma = 0;
                for (int i = 0, j = 11; j >= 2; i++, j--)
                {
                    soma += intCpf[i] * j;
                }
                int ultimoDigito = (soma * 10) % 11;
                if (ultimoDigito == 10)
                {
                    ultimoDigito = 0;
                }
                if (ultimoDigito != intCpf[10])
                {
                    ModelState.AddModelError("CPF", "O CPF inserido é inválido.");
                }
            }

            if (!string.IsNullOrEmpty(aluno.CPF) && repositorioAluno.GetAll().Any(alunoAdicionado => alunoAdicionado.CPF != null &&
                    alunoAdicionado.CPF.Equals(aluno.CPF) && !alunoAdicionado.Equals(aluno)))
            {
                ModelState.AddModelError("CPF", "CPF inserido já está sendo utilizado por outro aluno.");
            }
            if(!string.IsNullOrEmpty(aluno.Nascimento.ToString())){
#pragma warning disable CS8629 // Nullable value type may be null.
                if (aluno.Nascimento?.Day >= DateTime.DaysInMonth((int)(aluno.Nascimento?.Year), (int)(aluno.Nascimento?.Month)))
#pragma warning restore CS8629 // Nullable value type may be null.
                {
                    ModelState.AddModelError("Data de nascimento", "Dias devem seguir as regras de cada mês. Insira uma data válida.");
                }
            }            

            if(aluno.Matricula != null)
            {
                if (repositorioAluno.GetByMatricula((int)aluno.Matricula) != null)
                {
                    ModelState.AddModelError("Matricula", "Matrícula já está sendo utilizada por outro aluno.");
                }
                if (!Regex.IsMatch(aluno.Matricula.ToString(), "^[0-9]*$"))
                {
                    ModelState.AddModelError("Matricula", "Insira apenas números na matrícula.");
                }
            }

            if (ModelState.IsValid)
            {
                repositorioAluno.Add(aluno);
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        // GET: Aluno/Edit/5
        public ActionResult Edit(int matricula)
        {
            List<SelectListItem> sex_items = new()
            {
                new SelectListItem() { Text = "Masculino", Value = "Masculino" },
                new SelectListItem() { Text = "Feminino", Value = "Feminino" }
            };
            ViewBag.Sexo = sex_items;
            Aluno aluno = repositorioAluno.GetByMatricula(matricula);
            if(aluno == null)
            {
                ViewBag.Message = "Aluno não encontrado";
                return View();
            }
            return View(aluno);
        }

        // POST: Aluno/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(include: "Matricula, Nome, Sexo, Nascimento, CPF")] Aluno aluno)
        {
            List<SelectListItem> sex_items = new()
            {
                new SelectListItem() { Text = "Masculino", Value = "Masculino" },
                new SelectListItem() { Text = "Feminino", Value = "Feminino" }
            };
            ViewBag.Sexo = sex_items;

            if (!string.IsNullOrWhiteSpace(aluno.CPF))
            {
                string novoCpf = Regex.Replace(aluno.CPF, "[^0-9]", "");
                if (novoCpf.Length != 11)
                {
                    ModelState.AddModelError("CPF", "O CPF deve conter 11 dígitos.");
                    return View(aluno);
                }
                for (var i = 0; i < 11; i++)
                {
                    if (!char.IsDigit(novoCpf[i]))
                    {
                        ModelState.AddModelError("CPF", "O CPF deve conter apenas dígitos.");
                    }
                }
                var intCpf = new int[11];
                int soma = 0;
                for (int i = 0, j = 10; i < 11; i++, j--)
                {
                    var sucessoNaConversao = int.TryParse(novoCpf[i].ToString(), out var valor);
                    intCpf[i] = valor;
                    if (j >= 2 && sucessoNaConversao)
                    {
                        soma += intCpf[i] * j;
                    }
                }
                var cpfComTodosDigitosIguais = true;
                for (var i = 1; i < 11; i++)
                {
                    if (intCpf[0] != intCpf[i])
                    {
                        cpfComTodosDigitosIguais = false;
                        break;
                    }
                }
                if (cpfComTodosDigitosIguais)
                {
                    ModelState.AddModelError("CPF", "CPF's com todos dígitos iguais são inválidos.");
                }
                int penultimoDigito = (soma * 10) % 11;
                if (penultimoDigito == 10)
                {
                    penultimoDigito = 0;
                }
                if (penultimoDigito != intCpf[9])
                {
                    ModelState.AddModelError("CPF", "O CPF inserido é inválido.");
                }
                soma = 0;
                for (int i = 0, j = 11; j >= 2; i++, j--)
                {
                    soma += intCpf[i] * j;
                }
                int ultimoDigito = (soma * 10) % 11;
                if (ultimoDigito == 10)
                {
                    ultimoDigito = 0;
                }

WebTeste - Separado - Copia/WebTeste1/Views/Aluno/Create.cshtml
@model Aluno
@{
    ViewData["Title"] = "Cadastrar Aluno";
}
<h1 style="text-align: center">Cadastrar Aluno</h1>
<hr />

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @*<div class = "row">
            <div class="col-sm-2">
                @Html.LabelFor(model => model.Matricula)
                @Html.EditorFor(model => model.Matricula, new { htmlAttributes = new { @class = "form-control", oninput="javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);", @maxlength = "9", placeholder = "Matrícula do aluno", onkeypress = "return isNumberKey(event);" } })
                @Html.ValidationMessageFor(model => model.Matricula, "", new { @class = "text-danger" })    
            </div>
            <div class = "col-sm-10">
                @Html.LabelFor(model => model.Nome)
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", placeholder = "Nome do aluno" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class = "row">
            <div class = "col">
                @Html.LabelFor(model => model.Sexo)
                @Html.DropDownList("Sexo", (IEnumerable<SelectListItem>)ViewBag.Sex, "Selecione Sexo", htmlAttributes: new { @class = "form-control"})
                @Html.ValidationMessageFor(model => model.Sexo, "", new {@class = "text-danger"})
            </div>
            <div class = "col">
                @Html.LabelFor(model => model.Nascimento)
                @Html.EditorFor(model => model.Nascimento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nascimento, "", new { @class = "text-danger" })
            </div>
            <div class = "col">
                @Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "form-control", placeholder = "(Opcional) Apenas dígitos", onblur = "formataCPF(this)", data_tipo = "cpf" } })
                @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Matricula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Matricula, new { htmlAttributes = new { @class = "form-control", oninput="javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);", @maxlength = "9", placeholder = "Matrícula do aluno", onkeypress = "return isNumberKey(event);" } })
                @Html.ValidationMessageFor(model => model.Matricula, "", new { @class = "text-danger" })    
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", placeholder = "Nome do aluno" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Sexo", (IEnumerable<SelectListItem>)ViewBag.Sex, "Selecione Sexo", htmlAttributes: new { @class = "form-control"})
                @Html.ValidationMessageFor(model => model.Sexo, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nascimento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nascimento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "form-control", placeholder = "(Opcional) Apenas dígitos", /*onkeyup = "keyDownCpf(e)",*/ onkeyup = "formataCPF(this)", data_tipo = "cpf", @maxlength = "11" } })
                @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
            </div>
        </div>

        <br>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type = "button" class = "btn btn-danger" value = "Voltar" onclick="location.href='@Url.Action("Index", "Aluno")'" />
                <input type = "submit" value = "Cadastrar" class = "btn btn-dark"/>
            </div>
        </div>
    </div>
}

<script>
    function formataCPF(cpf) {
    const elementoAlvo = cpf
    const cpfAtual = cpf.value   

    let cpfAtualizado;

    cpfAtualizado = cpfAtual.replace(/(\d{3})(\d{3})(\d{3})(\d{2})/, 
    function( regex, argumento1, argumento2, argumento3, argumento4 ) {
        return argumento1 + '.' + argumento2 + '.' + argumento3 + '-' + argumento4; })  
    elementoAlvo.value = cpfAtualizado;
    }
</script>

@*<script>
    var keyEnabledArray = Array(222).fill(true);
    function onKeyDownCpf(e){
        if(keyEnabledArray[e.keyCode]) {
            keyEnabledArray[e.keyCode] = false;
        }
    }
</script>*@

<script>    
    $(document).ready(function() {
        $('#number').bind("cut copy paste drag drop", function(e) {
            e.preventDefault();
        });     
    });
    function isNumberKey(evt){
        var charCode = (evt.which) ? evt.which : evt.keyCode
        return !(charCode > 31 && (charCode < 48 || charCode > 57));
    }
</script>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

WebTeste - Separado - Copia/WebTeste1/Views/Aluno/Delete.cshtml
@model Aluno

@{
    ViewBag.Title = "Deletar aluno";
}

<h1 style="text-align: center">Tem certeza que deseja excluir esse aluno?</h1>
<hr />
<br />
    <div>
        <h4>Detalhes do aluno a ser excluído</h4>
        <form class = "form-group">
            <div class = "row">
                <div class="col p-3">
                    @Html.LabelFor(model => model.Nome)
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @readonly="readonly", @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class = "row">
                <div class="col p-3">
                    @Html.LabelFor(model => model.Matricula)
                    @Html.EditorFor(model => model.Matricula, new { htmlAttributes = new { @readonly="readonly", @class = "form-control"}})
                </div>

                <div class="col p-3">
                    @Html.LabelFor(model => model.Sexo)
                    @Html.EditorFor(model => model.Sexo, new { htmlAttributes = new { @readonly="readonly", @class = "form-control"} })
                    @Html.ValidationMessageFor(model => model.Sexo, "", new {@class = "text-danger"})
                </div>

                <div class= "col p-3">
                    @Html.LabelFor(model => model.Nascimento)
                    @Html.EditorFor(model => model.Nascimento, new { htmlAttributes = new { @readonly="readonly", @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nascimento, "", new { @class = "text-danger" })
                </div>

                <div class="col p-3">
                    @Html.LabelFor(model => model.CPF)
                    @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @readonly="readonly", @class = "form-control", data_tipo = "cpf"} })
                    @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
                </div>
            </div>
        </form>

        <br />
        <br />

        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
            <div class="form-group">
                <input type="button" class="btn btn-danger" value="Voltar" onclick="location.href='@Url.Action("Index", "Aluno")' " />
                <input type="submit" value="Excluir" class="btn btn-dark" />
            </div>
        }
    </div>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

WebTeste - Separado - Copia/WebTeste1/Views/Aluno/Edit.cshtml
@model Aluno
@{
    ViewData["Title"] = "Edit";
}

<h1 style="text-align: center">Atualizar Aluno</h1>
<hr/>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="row">

        @Html.HiddenFor(model => model.Matricula)
        <div class="form-group">
            @Html.LabelFor(model => model.Matricula, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Matricula, new { htmlAttributes = new { @readonly="readonly" , @class = "form-control" } })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", placeholder = "Nome do aluno" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.DropDownListFor(model => model.Sexo, (IEnumerable<SelectListItem>)ViewBag.Sex, htmlAttributes: new { @class = "form-control" } )
            @Html.ValidationMessageFor(model => model.Sexo, "", new {@class = "text-danger"})
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nascimento, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Nascimento, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nascimento, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "form-control" , placeholder = "(Opcional) Apenas dígitos", onkeyup = "formataCPF(this)", data_tipo = "cpf", @maxlength = "11"} })
            @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="button" class="btn btn-danger" value="Cancelar" onclick="location.href='@Url.Action("Index", "Aluno")'" />
            <input type="submit" value="Atualizar" class="btn btn-dark"/>
        </div>
    </div>
}

<script>
    function formataCPF(cpf) {
        const elementoAlvo = cpf
        const cpfAtual = cpf.value   

        let cpfAtualizado;

        cpfAtualizado = cpfAtual.replace(/(\d{3})(\d{3})(\d{3})(\d{2})/, 
        function( regex, argumento1, argumento2, argumento3, argumento4 ) {
                return argumento1 + '.' + argumento2 + '.' + argumento3 + '-' + argumento4; })  
        elementoAlvo.value = cpfAtualizado;
    }
</script>

WebTeste - Separado - Copia/WebTeste1/Views/Aluno/Index.cshtml
@model IEnumerable<Aluno>
@{
    ViewBag.Title = "Tabela de Alunos";
}

<div class="d-flex justify-content-between">
    <h1>Tabela de Alunos</h1>
    <input type="button" class="btn btn-dark" value="Adicionar aluno" onclick="location.href='@Url.Action("Create", "Aluno")'"/>    
</div>

<head>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
    />
</head>

<div class = "form-horizontal">
<hr />
    <form asp-controller="Aluno" asp-action="Index" method="get">
        <b> Opção de busca: </b> 
        <label for = "matricula">
            <input id = "matricula" name = "option" type = "radio" value = "Matricula" /> Matrícula
            @*@Html.RadioButton("option", "Matricula", false)<span> Matrícula</span>*@
        </label>
        <label for = "nome">
            <input id = "nome" name = "option" type = "radio" value = "Nome" /> Nome
        </label>
        @*@Html.RadioButton("option", "Nome", true) <span> Nome</span>*@
        <div id="divBusca">
            <input class = "form-control" placeholder = "Matrícula ou nome do aluno..." type = "text" name = "SearchString"/> <button id="btnBusca" class = "btn btn-dark">Buscar</button>
        </div>
    </form>
    <br />

<div style="overflow-x: auto;">
    <table class="table" id="tblAluno">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Matricula)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nome)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Sexo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nascimento)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CPF)
                </th>
                <th>
                    Opções
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Matricula)
                    </td>
                    <td style = "text-align: left">
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Sexo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nascimento)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CPF)
                    </td>
                    <td>
                        <div class = "editarExcluir">
                            <a href = "@Url.ActionLink("Edit", "Aluno", new { item.Matricula })">
                                <button type="button" class="btn btn-dark">
                                    <i class="bi bi-pencil text-light"></i> Editar
                                </button>
                            </a>
                            <a href = "@Url.ActionLink("Delete", "Aluno", new { item.Matricula })">
                                <button type="button" class= "btn btn-danger">
                                    <i class="bi bi-trash text-white"></i> Excluir
                                </button>
                            </a>
                        </div>
                    </td>
                </tr>
            }        
        </tbody>
    </table>
    </div>
</div>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js~/js/alunos.js"></script>